services:
  - type: web
    name: under1000k
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn under1000k.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: under1000k.onrender.com,localhost,127.0.0.1
      - key: STATIC_ROOT
        value: staticfiles
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_ROOT
        value: media
      - key: MEDIA_URL
        value: /media/
      - key: CSRF_COOKIE_SECURE
        value: false
      - key: SESSION_COOKIE_SECURE
        value: false
      - key: CSRF_COOKIE_SAMESITE
        value: Lax
      - key: SESSION_COOKIE_SAMESITE
        value: Lax 