# Generated by Django 5.2.4 on 2025-08-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealdetail',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Nivel de confianza del análisis (0-1)', max_digits=3),
        ),
    ]
